const functions = require('firebase-functions');
const admin = require('firebase-admin');
const nodemailer = require('nodemailer');

// Initialize Firebase Admin
admin.initializeApp();

// Create a transporter for sending emails
// You'll need to configure this with your email service
const transporter = nodemailer.createTransporter({
  service: 'gmail', // You can use other services like SendGrid, Mailgun, etc.
  auth: {
    user: functions.config().email.user, // Set this using: firebase functions:config:set email.user="your-email@gmail.com"
    pass: functions.config().email.password // Set this using: firebase functions:config:set email.password="your-app-password"
  }
});

// Cloud Function that triggers when a new contact is added to Firestore
exports.sendContactEmail = functions.firestore
  .document('contacts/{contactId}')
  .onCreate(async (snapshot, context) => {
    try {
      const contactData = snapshot.data();
      const { name, email, message, timestamp } = contactData;

      // Email content
      const mailOptions = {
        from: functions.config().email.user,
        to: functions.config().email.user, // Send to yourself
        subject: `New Contact Form Submission from ${name}`,
        html: `
          <div style="font-family: Arial, sans-serif; max-width: 600px; margin: 0 auto;">
            <h2 style="color: #333; border-bottom: 2px solid #007bff; padding-bottom: 10px;">
              New Contact Form Submission
            </h2>
            
            <div style="background: #f8f9fa; padding: 20px; border-radius: 5px; margin: 20px 0;">
              <h3 style="color: #007bff; margin-top: 0;">Contact Details:</h3>
              
              <table style="width: 100%; border-collapse: collapse;">
                <tr>
                  <td style="padding: 8px; border-bottom: 1px solid #ddd; font-weight: bold; width: 100px;">Name:</td>
                  <td style="padding: 8px; border-bottom: 1px solid #ddd;">${name}</td>
                </tr>
                <tr>
                  <td style="padding: 8px; border-bottom: 1px solid #ddd; font-weight: bold;">Email:</td>
                  <td style="padding: 8px; border-bottom: 1px solid #ddd;">
                    <a href="mailto:${email}" style="color: #007bff; text-decoration: none;">${email}</a>
                  </td>
                </tr>
                <tr>
                  <td style="padding: 8px; border-bottom: 1px solid #ddd; font-weight: bold;">Date:</td>
                  <td style="padding: 8px; border-bottom: 1px solid #ddd;">
                    ${timestamp ? new Date(timestamp.toDate()).toLocaleString() : new Date().toLocaleString()}
                  </td>
                </tr>
              </table>
            </div>

            <div style="background: #fff; padding: 20px; border: 1px solid #ddd; border-radius: 5px;">
              <h3 style="color: #007bff; margin-top: 0;">Message:</h3>
              <p style="line-height: 1.6; color: #333; white-space: pre-wrap;">${message}</p>
            </div>

            <div style="margin-top: 20px; padding: 15px; background: #e7f3ff; border-radius: 5px;">
              <p style="margin: 0; color: #0056b3;">
                <strong>Action Required:</strong> Please respond to this inquiry within 24 hours.
              </p>
            </div>

            <div style="margin-top: 30px; padding-top: 20px; border-top: 1px solid #ddd; text-align: center;">
              <p style="color: #666; font-size: 12px;">
                This email was automatically generated by your WebDev Services contact form.
              </p>
            </div>
          </div>
        `
      };

      // Send the email
      await transporter.sendMail(mailOptions);
      console.log(`Email sent successfully for contact from ${name}`);

      return { success: true, message: 'Email sent successfully' };

    } catch (error) {
      console.error('Error sending email:', error);
      throw new functions.https.HttpsError('internal', 'Unable to send email notification');
    }
  });

// Optional: Simple HTTP function to test email functionality
exports.testEmail = functions.https.onRequest(async (req, res) => {
  try {
    const mailOptions = {
      from: functions.config().email.user,
      to: functions.config().email.user,
      subject: 'Test Email from WebDev Services',
      text: 'This is a test email from your WebDev Services Firebase Function.'
    };

    await transporter.sendMail(mailOptions);
    res.status(200).send('Test email sent successfully!');
  } catch (error) {
    console.error('Error sending test email:', error);
    res.status(500).send('Error sending test email');
  }
});
